-- Run this query in your Supabase SQL Editor to create the appointments table

create table appointments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  email text,
  phone_number text,
  appointment_time text
);
